my_string = input('Введите текст: ')
print('Количество символов: ',(len(my_string)))
print('Текст в верхнем регистре:',my_string.upper())
print('Текст в нижнем регистре: ',my_string.lower())
print('Текст без пробелов: ',my_string.replace(' ',''))
print('Первый символ: ',my_string[0])
print('Последний символ: ',my_string[-1])
